local speed = -840
local score = -5

function update(self, dt)
	local p = go.get_position()
	p.x = p.x + speed * dt
	if p.x < -92 then
		go.delete()
	end
	go.set_position(p)
	go.set_scale(0.25,0.25,0.25)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if message.other_id == hash("/sausage_dog") then
			msg.post("main#gui", "add_score", {amount = score})
			go.delete()
		end
	end
end
