local speed = -640
local score = -5

function update(self, dt)
	local p = go.get_position()
	p.x = p.x + speed * dt
	if p.x < -92 then
		go.delete()
	end
	go.set_position(p)
	go.set_scale(0.2,0.2,0.2)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if message.other_id == hash("/sausage_dog") then
			msg.post("/main#gui", "add_score", {amount = score})
			msg.post("/main#gui", "remove_life", {})
			go.delete()
		end
	end
end
