function init(self)
	-- Let the script receive input from the player
	msg.post(".", "acquire_input_focus")
	
	

end


function update(self, dt)
	local p = go.get_position()
	
	if GAME_STARTED then
		go.animate("#sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_OUTSINE, 0.15, 2.5 , function () 
			
		end)
	
	
	end
	go.set_position(p)
end


function on_input(self, action_id, action)
	
	if action_id == hash("touch") then
        
        	go.delete(self)
	end
end


