local frequency = 0.75
local a = {2500,2550,2600}
local level = {"#building1","#building2","#building3","#building4","#building5","#building6"}



function init(self)
	self.timer = 0.5/frequency
end

function update(self, dt)
	self.timer = self.timer - dt
	if self.timer <= 0 then
		self.timer = 0.8/frequency
		local p = go.get_position()
		
		p.x = (a[math.random(1,#a)])
		p.z = 0
		local component = (level[math.random(1,#level)])
		local spawn = factory.create(component, p)
	end
	
end
