local score = 1
local speed = 180

function update(self, dt)
	local p = go.get_position()
	p.x = p.x - (speed + GLOBAL_SPEED) * dt
	if p.x < -32 then
		go.delete()
	end
	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if message.other_id == hash("/sausage_dog") then
			msg.post("main#gui", "add_score", {amount = score})
			go.delete()
		end
	end
end
